USEPKG += nanocbor

USEMODULE += libcose_crypt

USEMODULE += random

ifneq (,$(filter libcose_crypt_hacl,$(USEMODULE)))
  USEPKG += hacl
endif
ifneq (,$(filter libcose_crypt_c25519,$(USEMODULE)))
  USEPKG += c25519
endif
ifneq (,$(filter libcose_crypt_tinycrypt,$(USEMODULE)))
  USEPKG += tinycrypt
endif
ifneq (,$(filter libcose_crypt_monocypher,$(USEMODULE)))
  USEPKG += monocypher
endif
ifneq (,$(filter libcose_crypt_riot,$(USEMODULE)))
  USEMODULE += crypto
endif
ifneq (,$(filter libcose_crypt_wolfcrypt_mldsa,$(USEMODULE)))
  USEPKG += wolfssl
  USEMODULE += wolfcrypt
  USEMODULE += wolfcrypt_mldsa
endif
ifneq (,$(filter libcose_crypt_wolfcrypt_ecdsa,$(USEMODULE)))
  USEPKG += wolfssl
  USEMODULE += wolfcrypt
  USEMODULE += wolfcrypt_ecc
  # curve selection (wolfcrypt_ecc_p384 / _p521) is added by the caller, see
  # sys/suit/Makefile.dep - P-256 is wolfCrypt's baseline and always present
endif

DEFAULT_MODULE += libcose_crypt_init
DEFAULT_MODULE += auto_init_libcose_crypt
