/*
 * Device side of the firmware-encryption example: STREAMING decryption of a
 * detached-ciphertext COSE_Encrypt container produced by encrypt_firmware.py
 * (Python `cryptography`), using wolfCrypt's incremental ChaCha20-Poly1305
 * API. This mirrors, chunk for chunk, what the RIOT-side SUIT payload
 * decryptor does during a blockwise CoAP fetch:
 *
 *   1. buffer incoming 64-byte chunks until the self-delimiting CBOR header
 *      parses (the header typically straddles a chunk boundary),
 *   2. X25519 ECDH -> HKDF-SHA256 -> CEK, UpdateAad(Enc_structure),
 *   3. decrypt each chunk in place with wc_ChaCha20Poly1305_UpdateData,
 *      withholding the last 16 bytes seen so far (the trailing Poly1305 tag
 *      position is only known at end-of-stream) via a lag buffer,
 *   4. at end-of-stream: wc_ChaCha20Poly1305_Final + _CheckTag against the
 *      withheld 16 bytes — only then is the plaintext accepted.
 *
 * The container, the device's static X25519 private key, and the expected
 * plaintext are embedded via headers generated by encrypt_firmware.py
 * (encrypted.h, device_seckey.h, plaintext.h), so the binary is
 * self-contained. CBOR parsing uses nanocbor, same as the on-device parser.
 *
 * Build (against the pre-built wolfSSL checkout of the ml-dsa example,
 * already configured with --enable-curve25519, and RIOT's nanocbor):
 *   python3 encrypt_firmware.py
 *   gcc wolfcrypt-sample.c ../../../../build/pkg/nanocbor/src/decoder.c \
 *       ../../../../build/pkg/nanocbor/src/encoder.c \
 *       -o firmware-encryption-example \
 *       -I../../../../build/pkg/nanocbor/include \
 *       -I../../../../dist/tools/suit/ml-dsa-example/wolfssl \
 *       -L../../../../dist/tools/suit/ml-dsa-example/wolfssl/src/.libs \
 *       -Wl,-rpath,"$(realpath ../../../../dist/tools/suit/ml-dsa-example/wolfssl/src/.libs)" \
 *       -lwolfssl
 *
 * Run:
 *   ./firmware-encryption-example
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifndef WOLFSSL_USER_SETTINGS
    #include <wolfssl/options.h>
#endif

#include <wolfssl/wolfcrypt/settings.h>
#include <wolfssl/wolfcrypt/curve25519.h>
#include <wolfssl/wolfcrypt/hmac.h>
#include <wolfssl/wolfcrypt/chacha20_poly1305.h>
#include <wolfssl/wolfcrypt/error-crypt.h>

#include <nanocbor/nanocbor.h>

#include "encrypted.h"      /* const byte enc_stream[] (header||ct||tag) */
#include "device_seckey.h"  /* const byte device_seckey[32] */
#include "plaintext.h"      /* const byte expected_plaintext[] */

#define COSE_ALG_CHACHA20_POLY1305  24
#define COSE_ALG_ECDH_ES_HKDF_256  (-25)
#define COSE_TAG_ENCRYPT            96
#define COSE_HDR_IV                 5
#define COSE_KEY_PARAM_EPHEMERAL   (-1)
#define COSE_KEY_PARAM_X          (-2)

#define NONCE_LEN  CHACHA20_POLY1305_AEAD_IV_SIZE      /* 12 */
#define TAG_LEN    CHACHA20_POLY1305_AEAD_AUTHTAG_SIZE /* 16 */

/* COSE header buffer: an X25519 detached-ct header is ~110 B; sized like
 * the +128 B manifest-buffer bump, leaving CBOR-framing headroom */
#define HDR_BUF_LEN     192
/* transport chunk size to emulate (CoAP blockwise on the device) */
#define CHUNK_LEN       64

/* Parsed fields of the detached-ciphertext COSE_Encrypt header
 * (pointers into the header buffer) */
typedef struct {
    const uint8_t *body_protected;      /* serialized {1: 24} */
    size_t body_protected_len;
    const uint8_t *recipient_protected; /* serialized {1: -25} */
    size_t recipient_protected_len;
    const uint8_t *nonce;               /* 12 bytes */
    const uint8_t *ephemeral_pub;       /* 32 bytes */
} cose_hdr_t;

/* Streaming decrypt state — the same shape as the device-side
 * suit_payload_decrypt state */
typedef struct {
    uint8_t hdr[HDR_BUF_LEN];
    size_t hdr_fill;
    int hdr_done;
    cose_hdr_t msg;
    ChaChaPoly_Aead aead;
    uint8_t pending[TAG_LEN];   /* tag lag: last 16 bytes seen so far */
    size_t pending_fill;
    uint8_t *out;               /* plaintext sink (device: storage write) */
    size_t out_fill;
    size_t out_max;
} stream_state_t;

static int map_get_bstr(nanocbor_value_t *map, int32_t wanted,
                        const uint8_t **buf, size_t *len)
{
    while (!nanocbor_at_end(map)) {
        int32_t key;
        if (nanocbor_get_int32(map, &key) < 0) {
            return -1;
        }
        if (key == wanted) {
            return nanocbor_get_bstr(map, buf, len) < 0 ? -1 : 0;
        }
        if (nanocbor_skip(map) < 0) {
            return -1;
        }
    }
    return -1;
}

/* Drain a container iterator to its end so nanocbor_leave_container()
 * advances the parent cursor correctly (leave uses the child's cursor) */
static int drain(nanocbor_value_t *container)
{
    while (!nanocbor_at_end(container)) {
        if (nanocbor_skip(container) < 0) {
            return -1;
        }
    }
    return 0;
}

/* Parse the detached-ciphertext COSE_Encrypt header. Returns the header
 * length in bytes on success (the ciphertext stream starts right after),
 * or -1 if buf does not (yet) contain a complete, valid header — the
 * caller retries with more data until its buffer is exhausted.
 *
 * Every container is walked to its end and left properly: nanocbor_skip
 * does not descend into tagged items, so the only way to learn the exact
 * header length (= top-level cursor after leaving the outer array) is a
 * full unwind. This also validates completeness: any truncation fails a
 * get or skip call with ERR_END. */
static ssize_t parse_cose_header(const uint8_t *buf, size_t len,
                                 cose_hdr_t *msg)
{
    nanocbor_value_t it, body, map, recipients, recipient, key_map;
    uint32_t tag;
    size_t eph_len, nonce_len;

    nanocbor_decoder_init(&it, buf, len);
    if (nanocbor_get_tag(&it, &tag) < 0 || tag != COSE_TAG_ENCRYPT) {
        return -1;
    }
    if (nanocbor_enter_array(&it, &body) < 0 ||
        nanocbor_get_bstr(&body, &msg->body_protected,
                          &msg->body_protected_len) < 0) {
        return -1;
    }
    if (nanocbor_enter_map(&body, &map) < 0 ||
        map_get_bstr(&map, COSE_HDR_IV, &msg->nonce, &nonce_len) < 0 ||
        nonce_len != NONCE_LEN || drain(&map) < 0) {
        return -1;
    }
    nanocbor_leave_container(&body, &map);
    /* detached ciphertext: the slot must be null */
    if (nanocbor_get_null(&body) < 0) {
        return -1;
    }

    /* single recipient: [protected, {-1: COSE_Key}, h''] */
    if (nanocbor_enter_array(&body, &recipients) < 0 ||
        nanocbor_enter_array(&recipients, &recipient) < 0 ||
        nanocbor_get_bstr(&recipient, &msg->recipient_protected,
                          &msg->recipient_protected_len) < 0) {
        return -1;
    }
    if (nanocbor_enter_map(&recipient, &map) < 0) {
        return -1;
    }
    msg->ephemeral_pub = NULL;
    while (!nanocbor_at_end(&map)) {
        int32_t key;
        if (nanocbor_get_int32(&map, &key) < 0) {
            return -1;
        }
        if (key == COSE_KEY_PARAM_EPHEMERAL) {
            if (nanocbor_enter_map(&map, &key_map) < 0 ||
                map_get_bstr(&key_map, COSE_KEY_PARAM_X,
                             &msg->ephemeral_pub, &eph_len) < 0 ||
                eph_len != CURVE25519_KEYSIZE || drain(&key_map) < 0) {
                return -1;
            }
            nanocbor_leave_container(&map, &key_map);
        }
        else if (nanocbor_skip(&map) < 0) {
            return -1;
        }
    }
    if (msg->ephemeral_pub == NULL) {
        return -1;
    }
    nanocbor_leave_container(&recipient, &map);

    /* trailing encrypted-key slot (h'') + unwind all containers */
    if (drain(&recipient) < 0) {
        return -1;
    }
    nanocbor_leave_container(&recipients, &recipient);
    if (drain(&recipients) < 0) {
        return -1;
    }
    nanocbor_leave_container(&body, &recipients);
    if (!nanocbor_at_end(&body)) {
        return -1;
    }
    nanocbor_leave_container(&it, &body);
    return (ssize_t)(it.cur - buf);
}

/* HKDF info: COSE_KDF_Context (RFC 9053 5.2) — byte-identical to
 * encrypt_firmware.py: [24, [null,null,null], [null,null,null],
 *                       [256, <recipient protected header bstr>]] */
static int build_kdf_context(const cose_hdr_t *msg,
                             uint8_t *out, size_t out_len, size_t *written)
{
    nanocbor_encoder_t enc;
    nanocbor_encoder_init(&enc, out, out_len);
    nanocbor_fmt_array(&enc, 4);
    nanocbor_fmt_int(&enc, COSE_ALG_CHACHA20_POLY1305);
    for (int party = 0; party < 2; party++) {
        nanocbor_fmt_array(&enc, 3);
        for (int i = 0; i < 3; i++) {
            nanocbor_fmt_null(&enc);
        }
    }
    nanocbor_fmt_array(&enc, 2);
    nanocbor_fmt_uint(&enc, 256);
    nanocbor_put_bstr(&enc, msg->recipient_protected,
                      msg->recipient_protected_len);
    *written = nanocbor_encoded_len(&enc);
    return *written <= out_len ? 0 : -1;
}

/* AAD: Enc_structure (RFC 9052 5.3) ["Encrypt", <body protected bstr>, h''],
 * reusing the received protected-header bytes verbatim */
static int build_enc_structure(const cose_hdr_t *msg,
                               uint8_t *out, size_t out_len, size_t *written)
{
    nanocbor_encoder_t enc;
    nanocbor_encoder_init(&enc, out, out_len);
    nanocbor_fmt_array(&enc, 3);
    nanocbor_put_tstr(&enc, "Encrypt");
    nanocbor_put_bstr(&enc, msg->body_protected, msg->body_protected_len);
    nanocbor_put_bstr(&enc, (const uint8_t *)"", 0);
    *written = nanocbor_encoded_len(&enc);
    return *written <= out_len ? 0 : -1;
}

static int derive_cek(const cose_hdr_t *msg, byte *cek)
{
    int ret;
    curve25519_key device_key, ephemeral_key;
    WC_RNG rng;
    byte shared[CURVE25519_KEYSIZE];
    word32 shared_len = sizeof(shared);
    uint8_t info[64];
    size_t info_len;

    if (build_kdf_context(msg, info, sizeof(info), &info_len) < 0) {
        return -1;
    }

    ret = wc_InitRng(&rng);
    if (ret != 0) {
        return ret;
    }
    ret = wc_curve25519_init(&device_key);
    if (ret != 0) {
        wc_FreeRng(&rng);
        return ret;
    }
    ret = wc_curve25519_init(&ephemeral_key);
    if (ret != 0) {
        wc_curve25519_free(&device_key);
        wc_FreeRng(&rng);
        return ret;
    }

    /* cryptography.io uses RFC 7748 little-endian raw keys -> _ex variants
     * with EC25519_LITTLE_ENDIAN; blinding builds need the RNG hookup */
    ret = wc_curve25519_import_private_ex(device_seckey,
                                          sizeof(device_seckey),
                                          &device_key,
                                          EC25519_LITTLE_ENDIAN);
#ifdef WOLFSSL_CURVE25519_BLINDING
    if (ret == 0) {
        ret = wc_curve25519_set_rng(&device_key, &rng);
    }
#endif
    if (ret == 0) {
        ret = wc_curve25519_import_public_ex(msg->ephemeral_pub,
                                             CURVE25519_KEYSIZE,
                                             &ephemeral_key,
                                             EC25519_LITTLE_ENDIAN);
    }
    if (ret == 0) {
        ret = wc_curve25519_shared_secret_ex(&device_key, &ephemeral_key,
                                             shared, &shared_len,
                                             EC25519_LITTLE_ENDIAN);
    }
    if (ret == 0) {
        ret = wc_HKDF(WC_SHA256, shared, shared_len, NULL, 0,
                      info, (word32)info_len,
                      cek, CHACHA20_POLY1305_AEAD_KEYSIZE);
    }

    memset(shared, 0, sizeof(shared));
    wc_curve25519_free(&ephemeral_key);
    wc_curve25519_free(&device_key);
    wc_FreeRng(&rng);
    return ret;
}

/* Feed ciphertext bytes into the AEAD, always withholding the most recent
 * TAG_LEN bytes (candidate trailing tag) in s->pending */
static int feed_ciphertext(stream_state_t *s, const uint8_t *data, size_t len)
{
    size_t total = s->pending_fill + len;

    if (total > TAG_LEN) {
        size_t n = total - TAG_LEN;             /* safely decryptable */
        size_t from_pending = n < s->pending_fill ? n : s->pending_fill;

        if (from_pending > 0) {
            uint8_t tmp[TAG_LEN];
            if (s->out_fill + from_pending > s->out_max) {
                return -1;
            }
            if (wc_ChaCha20Poly1305_UpdateData(&s->aead, s->pending, tmp,
                                               (word32)from_pending) != 0) {
                return -1;
            }
            memcpy(s->out + s->out_fill, tmp, from_pending);
            s->out_fill += from_pending;
            memmove(s->pending, s->pending + from_pending,
                    s->pending_fill - from_pending);
            s->pending_fill -= from_pending;
        }

        size_t from_data = n - from_pending;
        if (from_data > 0) {
            if (s->out_fill + from_data > s->out_max) {
                return -1;
            }
            if (wc_ChaCha20Poly1305_UpdateData(&s->aead, data,
                                               s->out + s->out_fill,
                                               (word32)from_data) != 0) {
                return -1;
            }
            s->out_fill += from_data;
            data += from_data;
            len -= from_data;
        }
    }

    /* stash the (potential) tag tail */
    memcpy(s->pending + s->pending_fill, data, len);
    s->pending_fill += len;
    return 0;
}

/* Process one transport chunk; more=0 signals end-of-stream (tag check) */
static int stream_chunk(stream_state_t *s, const uint8_t *buf, size_t len,
                        int more)
{
    if (!s->hdr_done && len > 0) {
        size_t space = sizeof(s->hdr) - s->hdr_fill;
        size_t take = len < space ? len : space;
        if (take == 0) {
            printf("header exceeds %d-byte buffer\n", HDR_BUF_LEN);
            return -1;
        }
        memcpy(s->hdr + s->hdr_fill, buf, take);
        s->hdr_fill += take;
        buf += take;
        len -= take;

        ssize_t hdr_len = parse_cose_header(s->hdr, s->hdr_fill, &s->msg);
        if (hdr_len < 0) {
            if (len > 0) {          /* buffer full yet still unparseable */
                printf("COSE header parsing failed\n");
                return -1;
            }
            return 0;               /* incomplete: wait for the next chunk */
        }

        byte cek[CHACHA20_POLY1305_AEAD_KEYSIZE];
        uint8_t aad[64];
        size_t aad_len;
        int ret = derive_cek(&s->msg, cek);
        if (ret != 0) {
            printf("CEK derivation failed: %d\n", ret);
            return -1;
        }
        if (build_enc_structure(&s->msg, aad, sizeof(aad), &aad_len) < 0 ||
            wc_ChaCha20Poly1305_Init(&s->aead, cek, s->msg.nonce,
                                     CHACHA20_POLY1305_AEAD_DECRYPT) != 0 ||
            wc_ChaCha20Poly1305_UpdateAad(&s->aead, aad,
                                          (word32)aad_len) != 0) {
            memset(cek, 0, sizeof(cek));
            return -1;
        }
        memset(cek, 0, sizeof(cek));
        s->hdr_done = 1;

        /* bytes past the header already sitting in the header buffer are
         * the first ciphertext bytes */
        if (s->hdr_fill > (size_t)hdr_len) {
            if (feed_ciphertext(s, s->hdr + hdr_len,
                                s->hdr_fill - hdr_len) < 0) {
                return -1;
            }
        }
    }

    if (len > 0) {
        if (!s->hdr_done) {
            return 0;   /* unreachable: header consumes whole early chunks */
        }
        if (feed_ciphertext(s, buf, len) < 0) {
            return -1;
        }
    }

    if (!more) {
        byte computed[TAG_LEN];
        if (!s->hdr_done || s->pending_fill != TAG_LEN) {
            printf("stream truncated (no trailing tag)\n");
            return -1;
        }
        if (wc_ChaCha20Poly1305_Final(&s->aead, computed) != 0) {
            return -1;
        }
        if (wc_ChaCha20Poly1305_CheckTag(computed, s->pending) != 0) {
            return -1;  /* MAC_CMP_FAILED_E */
        }
    }
    return 0;
}

/* Run the full stream through the state machine in CHUNK_LEN pieces,
 * emulating the device's blockwise fetch (last chunk carries more=0) */
static int run_stream(const uint8_t *stream, size_t stream_len,
                      uint8_t *out, size_t out_max, size_t *out_len)
{
    stream_state_t *s = calloc(1, sizeof(*s));
    if (s == NULL) {
        return -1;
    }
    s->out = out;
    s->out_max = out_max;

    int ret = 0;
    for (size_t off = 0; off < stream_len && ret == 0; off += CHUNK_LEN) {
        size_t len = stream_len - off < CHUNK_LEN ? stream_len - off
                                                  : CHUNK_LEN;
        int more = (off + len < stream_len);
        ret = stream_chunk(s, stream + off, len, more);
    }
    *out_len = s->out_fill;
    free(s);
    return ret;
}

int main(void)
{
    size_t out_len = 0;
    uint8_t *out = malloc(sizeof(expected_plaintext) + CHUNK_LEN);

    printf("Streaming COSE_Encrypt firmware decryption with wolfCrypt "
           "- START\n");
    printf("Stream: %u bytes, fed in %u-byte chunks\n",
           (unsigned)sizeof(enc_stream), (unsigned)CHUNK_LEN);

    if (out == NULL) {
        printf("malloc failed\n");
        return 1;
    }

    /* Positive case */
    if (run_stream(enc_stream, sizeof(enc_stream), out,
                   sizeof(expected_plaintext) + CHUNK_LEN, &out_len) != 0) {
        printf("streaming decrypt FAILED\n");
        return 1;
    }
    if (out_len == sizeof(expected_plaintext) &&
        memcmp(out, expected_plaintext, out_len) == 0) {
        printf("Python-encrypted, wolfCrypt-stream-decrypted: MATCH "
               "(%u bytes)\n", (unsigned)out_len);
    }
    else {
        printf("Python-encrypted, wolfCrypt-stream-decrypted: MISMATCH\n");
        return 1;
    }

    /* Negative tests: each tamper must be rejected at the final tag check */
    struct {
        const char *what;
        size_t index;               /* byte to flip within the stream */
    } cases[] = {
        { "ciphertext byte", sizeof(enc_stream) / 2 },
        { "trailing tag byte", sizeof(enc_stream) - 1 },
        { "header nonce byte", 12 },
    };
    uint8_t *tampered = malloc(sizeof(enc_stream));
    if (tampered == NULL) {
        printf("malloc failed\n");
        return 1;
    }
    for (size_t i = 0; i < sizeof(cases) / sizeof(cases[0]); i++) {
        memcpy(tampered, enc_stream, sizeof(enc_stream));
        tampered[cases[i].index] ^= 0x01;
        int ret = run_stream(tampered, sizeof(enc_stream), out,
                             sizeof(expected_plaintext) + CHUNK_LEN,
                             &out_len);
        printf("Tampered %s rejected: %s\n", cases[i].what,
               ret != 0 ? "YES" : "NO - BUG");
        if (ret == 0) {
            return 1;
        }
    }
    free(tampered);
    free(out);

    printf("Streaming COSE_Encrypt firmware decryption with wolfCrypt "
           "- END\n");
    return 0;
}
