/*
 * Device side of the manifest-encryption example: decrypt an RFC 9770-style
 * COSE_Encrypt container produced by encrypt_manifest.py (Python
 * `cryptography`) using wolfCrypt, proving cross-implementation interop of
 * the full pipeline: X25519 ECDH -> HKDF-SHA256 -> ChaCha20-Poly1305.
 *
 * The container, the device's static X25519 private key, and the expected
 * plaintext are embedded via headers generated by encrypt_manifest.py
 * (encrypted.h, device_seckey.h, plaintext.h), so the binary is
 * self-contained. CBOR parsing/encoding uses nanocbor, the same library the
 * on-device SUIT parser uses.
 *
 * Build (against the pre-built wolfSSL checkout in the ml-dsa example,
 * reconfigured with --enable-curve25519, and RIOT's nanocbor checkout):
 *   python3 encrypt_manifest.py
 *   gcc wolfcrypt-sample.c ../../../../build/pkg/nanocbor/src/decoder.c \
 *       ../../../../build/pkg/nanocbor/src/encoder.c \
 *       -o manifest-encryption-example \
 *       -I../../../../build/pkg/nanocbor/include \
 *       -I../../../../dist/tools/suit/ml-dsa-example/wolfssl \
 *       -L../../../../dist/tools/suit/ml-dsa-example/wolfssl/src/.libs \
 *       -Wl,-rpath,"$(realpath ../../../../dist/tools/suit/ml-dsa-example/wolfssl/src/.libs)" \
 *       -lwolfssl
 *
 * Run:
 *   ./manifest-encryption-example
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifndef WOLFSSL_USER_SETTINGS
    #include <wolfssl/options.h>
#endif

#include <wolfssl/wolfcrypt/settings.h>
#include <wolfssl/wolfcrypt/curve25519.h>
#include <wolfssl/wolfcrypt/hmac.h>
#include <wolfssl/wolfcrypt/chacha20_poly1305.h>
#include <wolfssl/wolfcrypt/error-crypt.h>

#include <nanocbor/nanocbor.h>

#include "encrypted.h"      /* const byte cose_encrypt[] */
#include "device_seckey.h"  /* const byte device_seckey[32] */
#include "plaintext.h"      /* const byte expected_plaintext[] */

#define COSE_ALG_CHACHA20_POLY1305  24
#define COSE_ALG_ECDH_ES_HKDF_256  (-25)
#define COSE_TAG_ENCRYPT            96
#define COSE_HDR_IV                 5
#define COSE_KEY_PARAM_EPHEMERAL   (-1)
#define COSE_KEY_PARAM_X          (-2)

#define NONCE_LEN  CHACHA20_POLY1305_AEAD_IV_SIZE      /* 12 */
#define TAG_LEN    CHACHA20_POLY1305_AEAD_AUTHTAG_SIZE /* 16 */

/* Parsed fields of the COSE_Encrypt container (pointers into cose_encrypt) */
typedef struct {
    const uint8_t *body_protected;      /* serialized {1: 24} */
    size_t body_protected_len;
    const uint8_t *recipient_protected; /* serialized {1: -25} */
    size_t recipient_protected_len;
    const uint8_t *nonce;               /* 12 bytes */
    const uint8_t *ciphertext;          /* without the trailing tag */
    size_t ciphertext_len;
    const uint8_t *auth_tag;            /* 16 bytes */
    const uint8_t *ephemeral_pub;       /* 32 bytes */
} cose_encrypt_msg_t;

static void print_hex(const char *label, const byte *data, word32 len)
{
    word32 i;
    printf("%s (%u bytes): ", label, (unsigned)len);
    for (i = 0; i < len && i < 32; i++) {       /* print first 32 bytes only */
        printf("%02x", data[i]);
    }
    if (len > 32) printf("...");
    printf("\n");
}

/* Fetch the value for `wanted` from a CBOR map, skipping other entries */
static int map_get_bstr(nanocbor_value_t *map, int32_t wanted,
                        const uint8_t **buf, size_t *len)
{
    while (!nanocbor_at_end(map)) {
        int32_t key;
        if (nanocbor_get_int32(map, &key) < 0) {
            return -1;
        }
        if (key == wanted) {
            return nanocbor_get_bstr(map, buf, len) < 0 ? -1 : 0;
        }
        if (nanocbor_skip(map) < 0) {
            return -1;
        }
    }
    return -1;
}

static int parse_cose_encrypt(const uint8_t *buf, size_t len,
                              cose_encrypt_msg_t *msg)
{
    nanocbor_value_t it, body, map, recipients, recipient, key_map;
    uint32_t tag;
    const uint8_t *ct;
    size_t ct_len, eph_len, nonce_len;

    nanocbor_decoder_init(&it, buf, len);
    if (nanocbor_get_tag(&it, &tag) < 0 || tag != COSE_TAG_ENCRYPT) {
        printf("not a COSE_Encrypt (tag 96) container\n");
        return -1;
    }
    if (nanocbor_enter_array(&it, &body) < 0 ||
        nanocbor_get_bstr(&body, &msg->body_protected,
                          &msg->body_protected_len) < 0) {
        return -1;
    }
    if (nanocbor_enter_map(&body, &map) < 0 ||
        map_get_bstr(&map, COSE_HDR_IV, &msg->nonce, &nonce_len) < 0 ||
        nonce_len != NONCE_LEN) {
        printf("missing/invalid IV in unprotected header\n");
        return -1;
    }
    nanocbor_leave_container(&body, &map);
    if (nanocbor_get_bstr(&body, &ct, &ct_len) < 0 || ct_len < TAG_LEN) {
        return -1;
    }
    msg->ciphertext = ct;
    msg->ciphertext_len = ct_len - TAG_LEN;
    msg->auth_tag = ct + ct_len - TAG_LEN;

    /* single recipient: [protected, {-1: COSE_Key}, h''] */
    if (nanocbor_enter_array(&body, &recipients) < 0 ||
        nanocbor_enter_array(&recipients, &recipient) < 0 ||
        nanocbor_get_bstr(&recipient, &msg->recipient_protected,
                          &msg->recipient_protected_len) < 0) {
        return -1;
    }
    if (nanocbor_enter_map(&recipient, &map) < 0) {
        return -1;
    }
    while (!nanocbor_at_end(&map)) {
        int32_t key;
        if (nanocbor_get_int32(&map, &key) < 0) {
            return -1;
        }
        if (key == COSE_KEY_PARAM_EPHEMERAL) {
            if (nanocbor_enter_map(&map, &key_map) < 0 ||
                map_get_bstr(&key_map, COSE_KEY_PARAM_X,
                             &msg->ephemeral_pub, &eph_len) < 0 ||
                eph_len != CURVE25519_KEYSIZE) {
                printf("missing/invalid ephemeral key\n");
                return -1;
            }
            return 0;
        }
        if (nanocbor_skip(&map) < 0) {
            return -1;
        }
    }
    printf("no ephemeral key in recipient header\n");
    return -1;
}

/* HKDF info: COSE_KDF_Context (RFC 9053 5.2) — must match encrypt_manifest.py
 * byte-for-byte: [24, [null,null,null], [null,null,null],
 *                 [256, <recipient protected header bstr>]] */
static int build_kdf_context(const cose_encrypt_msg_t *msg,
                             uint8_t *out, size_t out_len, size_t *written)
{
    nanocbor_encoder_t enc;
    nanocbor_encoder_init(&enc, out, out_len);
    nanocbor_fmt_array(&enc, 4);
    nanocbor_fmt_int(&enc, COSE_ALG_CHACHA20_POLY1305);
    for (int party = 0; party < 2; party++) {
        nanocbor_fmt_array(&enc, 3);
        for (int i = 0; i < 3; i++) {
            nanocbor_fmt_null(&enc);
        }
    }
    nanocbor_fmt_array(&enc, 2);
    nanocbor_fmt_uint(&enc, 256);
    nanocbor_put_bstr(&enc, msg->recipient_protected,
                      msg->recipient_protected_len);
    *written = nanocbor_encoded_len(&enc);
    return *written <= out_len ? 0 : -1;
}

/* AAD: Enc_structure (RFC 9052 5.3) ["Encrypt", <body protected bstr>, h''],
 * reusing the received protected-header bytes verbatim */
static int build_enc_structure(const cose_encrypt_msg_t *msg,
                               uint8_t *out, size_t out_len, size_t *written)
{
    nanocbor_encoder_t enc;
    nanocbor_encoder_init(&enc, out, out_len);
    nanocbor_fmt_array(&enc, 3);
    nanocbor_put_tstr(&enc, "Encrypt");
    nanocbor_put_bstr(&enc, msg->body_protected, msg->body_protected_len);
    nanocbor_put_bstr(&enc, (const uint8_t *)"", 0);
    *written = nanocbor_encoded_len(&enc);
    return *written <= out_len ? 0 : -1;
}

static int derive_cek(const cose_encrypt_msg_t *msg, byte *cek)
{
    int ret;
    curve25519_key device_key, ephemeral_key;
    WC_RNG rng;
    byte shared[CURVE25519_KEYSIZE];
    word32 shared_len = sizeof(shared);
    uint8_t info[64];
    size_t info_len;

    if (build_kdf_context(msg, info, sizeof(info), &info_len) < 0) {
        printf("KDF context encoding failed\n");
        return -1;
    }

    ret = wc_InitRng(&rng);
    if (ret != 0) {
        return ret;
    }
    ret = wc_curve25519_init(&device_key);
    if (ret != 0) {
        wc_FreeRng(&rng);
        return ret;
    }
    ret = wc_curve25519_init(&ephemeral_key);
    if (ret != 0) {
        wc_curve25519_free(&device_key);
        wc_FreeRng(&rng);
        return ret;
    }

    /* cryptography.io exchanges RFC 7748 little-endian raw keys, so all
     * import/exchange calls must use the _ex variants with
     * EC25519_LITTLE_ENDIAN (wolfCrypt defaults to big-endian) */
    ret = wc_curve25519_import_private_ex(device_seckey,
                                          sizeof(device_seckey),
                                          &device_key,
                                          EC25519_LITTLE_ENDIAN);
#ifdef WOLFSSL_CURVE25519_BLINDING
    /* this build blinds the scalar multiplication (side-channel hardening,
     * on by default for the C-only implementation) — that needs entropy */
    if (ret == 0) {
        ret = wc_curve25519_set_rng(&device_key, &rng);
    }
#endif
    if (ret == 0) {
        ret = wc_curve25519_import_public_ex(msg->ephemeral_pub,
                                             CURVE25519_KEYSIZE,
                                             &ephemeral_key,
                                             EC25519_LITTLE_ENDIAN);
    }
    if (ret == 0) {
        ret = wc_curve25519_shared_secret_ex(&device_key, &ephemeral_key,
                                             shared, &shared_len,
                                             EC25519_LITTLE_ENDIAN);
    }
    if (ret == 0) {
        print_hex("Shared secret", shared, shared_len);
        ret = wc_HKDF(WC_SHA256, shared, shared_len, NULL, 0,
                      info, (word32)info_len,
                      cek, CHACHA20_POLY1305_AEAD_KEYSIZE);
    }

    memset(shared, 0, sizeof(shared));
    wc_curve25519_free(&ephemeral_key);
    wc_curve25519_free(&device_key);
    wc_FreeRng(&rng);
    return ret;
}

int main(void)
{
    int ret;
    cose_encrypt_msg_t msg;
    byte cek[CHACHA20_POLY1305_AEAD_KEYSIZE];
    uint8_t aad[64];
    size_t aad_len;
    byte *plain;

    printf("COSE_Encrypt manifest decryption with wolfCrypt - START\n");

    if (parse_cose_encrypt(cose_encrypt, sizeof(cose_encrypt), &msg) < 0) {
        printf("COSE_Encrypt parsing failed\n");
        return 1;
    }
    print_hex("Ephemeral pubkey", msg.ephemeral_pub, CURVE25519_KEYSIZE);
    print_hex("Nonce", msg.nonce, NONCE_LEN);
    print_hex("Ciphertext", msg.ciphertext, (word32)msg.ciphertext_len);

    ret = derive_cek(&msg, cek);
    if (ret != 0) {
        printf("CEK derivation failed: %d\n", ret);
        return 1;
    }

    if (build_enc_structure(&msg, aad, sizeof(aad), &aad_len) < 0) {
        printf("Enc_structure encoding failed\n");
        return 1;
    }

    plain = (byte *)malloc(msg.ciphertext_len);
    if (plain == NULL) {
        printf("malloc failed\n");
        return 1;
    }

    ret = wc_ChaCha20Poly1305_Decrypt(cek, msg.nonce, aad, (word32)aad_len,
                                      msg.ciphertext,
                                      (word32)msg.ciphertext_len,
                                      msg.auth_tag, plain);
    if (ret != 0) {
        printf("wc_ChaCha20Poly1305_Decrypt failed: %d\n", ret);
        free(plain);
        return 1;
    }

    printf("\nRecovered plaintext (%u bytes): %.*s\n",
           (unsigned)msg.ciphertext_len,
           (int)msg.ciphertext_len, (const char *)plain);
    if (msg.ciphertext_len == sizeof(expected_plaintext) &&
        memcmp(plain, expected_plaintext, sizeof(expected_plaintext)) == 0) {
        printf("Python-encrypted, wolfCrypt-decrypted: MATCH\n");
    }
    else {
        printf("Python-encrypted, wolfCrypt-decrypted: MISMATCH\n");
        free(plain);
        return 1;
    }

    /* Negative test: a single flipped ciphertext byte must fail the tag */
    {
        byte *tampered = (byte *)malloc(msg.ciphertext_len);
        if (tampered == NULL) {
            printf("malloc failed\n");
            free(plain);
            return 1;
        }
        memcpy(tampered, msg.ciphertext, msg.ciphertext_len);
        tampered[0] ^= 0x01;
        ret = wc_ChaCha20Poly1305_Decrypt(cek, msg.nonce, aad,
                                          (word32)aad_len, tampered,
                                          (word32)msg.ciphertext_len,
                                          msg.auth_tag, plain);
        printf("Tampered ciphertext rejected: %s (ret %d)\n",
               ret != 0 ? "YES" : "NO - BUG", ret);
        free(tampered);
        if (ret == 0) {
            free(plain);
            return 1;
        }
    }

    free(plain);
    printf("COSE_Encrypt manifest decryption with wolfCrypt - END\n");
    return 0;
}
